### PR TITLE
Producer message ordering guarantees on single partition

### PR DESCRIPTION
**Pull request by seglo**
Reproducer for #137

### CODE REVIEW

**Review by ernani — COMMENTED** [review]
LGTM

**Comment by germanenik** [comment]
facing the same issue even after I changed the kafka version to 2.3.0 locally

**Review by ernani — APPROVED** [review]
I do think that the thread sleep here is really making a difference in ensuring ordering, but, IMHO, kafka doesn't take much care about ordering with multiple partitions, that should be checked in the code to make sure it is at least eventual consistency...It will ensure delivery at some point.

**Comment by germanenik** [comment]
following the article @ernani shared with me (https://blog.softwaremill.com/does-kafka-really-guarantee-the-order-of-messages-3ca849fd19d2), adding this to producer.config solved ordering inconsistencies for me
`acks=all
enable.idempotence=true`

**Pull request merged**
