### PR TITLE
Added a Go quickstart using Sarama Kafka client

### PR DESCRIPTION
**Pull request by abhirockzz**
Example of how to connect to Event Hubs Kafka using the [Sarama Go client library](https://github.com/Shopify/sarama) for Kafka

### CODE REVIEW

**Comment by abhirockzz** [comment]
ping @arerlend 😃

**Comment by arerlend** [comment]
Awesome, running it now but have a few things on my plate right now.  Should approve no later than midday PST tomorrow.

Thanks for the contribution!

**Comment by abhirockzz** [comment]
Sounds good @arerlend ! Do you think this is better off being part of 'tutorials' section rather than the `quickstart`?

**Comment by arerlend** [comment]
Quickstart is where we put the language-based guides, so that works well.

**Pull request merged**
